# Generated by Django 5.2.5 on 2025-12-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='restaurant_logos/')),
                ('address', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('avg_cost', models.CharField(blank=True, max_length=100)),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('must_try', models.CharField(blank=True, max_length=255)),
                ('timings', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('social', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
