# Generated by Django 4.2.16 on 2026-03-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_category_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
