# Generated by Django 4.2.16 on 2026-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/logos/'),
        ),
    ]
