# Generated by Django 4.2.16 on 2026-03-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
