# Generated by Django 4.2.16 on 2026-03-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_food_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='theme',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='avg_cost',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='must_try',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='social',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='theme',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurantrequest',
            name='timings',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
